### ISSUE TITLE
Cross-realm weak references

### ISSUE THREAD

**Issue by dtribble** [tc39/proposal-weakrefs#10]
Raised at TC39.

Can we support cross-realm weak references?

**Comment by erights** [comment]
See https://mail.mozilla.org/pipermail/es-discuss/2013-January/028542.html 
This is the solution mentioned in that TC39 discussion and in the cross-realm weakrefs discussion section on this weakrefs spec. I think it is clean and does solve the problem. 

Should this proposal be expanded to include this solution, or should this solution become a separate proposal? I am not opposed to expanding this spec to include this solution. But I prefer a separate proposal, since the current proposal is consistent without it and this solution covers a narrow use-case that is rarely encountered in practice.

**Comment by dtribble** [comment]
@erights The "implementation" as-is would allow invoking a makeWeakRef from another realm to construct WeakRefs on that realm's objects. And it would work through a membrane as well.

The main reason we might need to include this is to make sure it's compatible. In the "implementation", the cross realm decision is in 
`if (REALM_OF(target) === REALM_OF(makeWeakRef)) {`

That could test a collection of realms that the weak reference factory closes over. Since that suppotr could be added later, I agree this could be separate. What are the use cases for it?

**Comment by erights** [comment]
First, there probably are no interesting use cases involving "internal" use of weak references, since such internal uses are likely to be within the same realm.

However, some applications already mix realms via same-origin iframes, and such mixing will increase with frozen-realms. Within such multi-realm apps, "external" uses of weak references will want to include all objects from that set of intertwingled realms.

**Comment by littledan** [comment]
The current proposal supports cross-realm WeakRefs, see #52.
