### ISSUE TITLE
Will heldValue be GC, after cleanupCallback executed?

### ISSUE THREAD

**Issue by LongTengDao** [tc39/proposal-weakrefs#220]
```js
const fr = new FinalizationRegistry( function cleanupCallback (heldObject) { /* do something... */ } );

fr.register(targetObject, heldObject);
```

I see "If the held value is an object, the registry keeps a strong reference to it" in the MDN.

I want to clarify, does the strong reference still exist after the cleanup callback executed? Or it will be GC (if there are no where else reference the held value in the program)?

**Comment by mhofman** [comment]
Since this proposal is now stage 4, a better place for this question would be Stack Overflow.

The short answer is no, there is no longer a strong reference, and it can be GCed if no longer referenced by any other part of the program.

For the long answer, the FinalizationRegistry holds onto the `heldValue` (it doesn't have to be an object) while the registration cell exists. As soon as the cell is removed from the registry, whether because it was unregistered by the program or because the target was collected and the callback was made, the registry no longer has a reference to the cell and its held value.
