### ISSUE TITLE
When should DoAgentFinalization be called?

### ISSUE THREAD

**Issue by gsathya** [tc39/proposal-weakrefs#36]
Is this something that should be embedder defined?

cc @dtribble @erights @marjakh

**Comment by tschneidereit** [comment]
The timing of `DoAgentFinalization` should probably be wholly implementation defined. In practice, I'd expect it to happen at the end of the sweep phase, but for engines with incremental or concurrent sweeping, there's no fundamental reason why it couldn't happen after each slice/in the process of the concurrent sweeping.

The results of this become visible through `cleanupSome`, which should probably always invoke the callback, and whose iterator should yield items as long as the queue isn't empty.

Another question is when this queue should be processed automatically, invoking the `cleanup` callback passed to the `WeakFactory`'s constructor. On that, I think we should specify that it must not happen before the end of the current task, but that otherwise the timing is implementation defined, too.

**Comment by marjakh** [comment]
DoAgentFinalization seems to assume to have a current Realm ("native context") though, and during GC there's none. See also https://github.com/tc39/proposal-weakrefs/issues/38 for a suggested fix.

**Comment by littledan** [comment]
We ended up making this call embedder-defined. See https://github.com/tc39/proposal-weakrefs/pull/86 for details.
